.TH SPIX 1 "Dec 2024" "" "General Commands Manual"
.nh
.ad l
.
.SH NAME
spixx \- Spinner
.
.SH SYNOPSIS
.B spix
.RI [ OPTION ]...
.RI [ ARG ]
.
.SH DESCRIPTION
spix is a command line (CLI) tool written in C++ that displays an animated spinner while a background process is running. It is useful for visually indicating that a task is in progress, especially if the task takes a considerable amount of time.
.
.SH OPTIONS
.
.SS General options:
.TP
.B -v, --version
Show version 
.TP
.B -h, --help
Display help and exit
.TP
.B -t TEXT, --text=TEXT
Text to show
.TP
.B -i INT, --interval=INT
Interval in milliseconds
.TP
.B -s STRING, --symbols=STRING
Symbols the spinner
.TP
.B -p COMMAND, --process=COMMAND
Command to execute
.TP
.B -l, --list_symbols
List available spinner symbols
.TP
.B -c, --color
Change text color
.TP
.B --list_colors
Show list colors 

.SH EXAMPLES 
spix -t "Hola Mundo" -c 105 

.SH SEE ALSO
https://victorh028.github.io/spix/ 

