.TH SPIX 1 "Dec 2023" "" "General Commands Manual"
.nh
.ad l
.
.SH NAME
.
spix \- Spinner
.
.SH SYNOPSIS
.
.B spix
.RI [ OPTION ]...\&
.RI [ ARG ]
.
.SH OPTIONS
.
.SS General options:
.
.TP
.BR -h ", " --help
Display help and exit
.
.TP
.BR -t ", " --version
Display version and exit
.
.SS Configutacion:
.
.TP
.B --name-user
Change username (default i-haklab)
.
.TP
.B --A
aaaaaa
.
.PP
Note: probando.
.
.SS dpkg:
.
.TP
.B --f
C
.
.SH SEE ALSO
.
https://victorh028.github.io/spix/
.
